# Generated by Django 3.0.5 on 2020-05-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
